---
title: "Project6"
author: "Baijayanti"
date: "21/12/2019"
output: word_document
---

```{r setup, include=TRUE}
#Include the libraries
library(forecast)
library(imputeTS)
library(TSstudio)
library(TSA)
library(fpp2)
library(readxl)
library(ggplot2)
library(tseries)
library(tidyverse)
library(rio)
library(dplyr)
library(reshape2)
library(chron)
library(pear)
library(StatMeasures)
library(vars)
library(MLmetrics)
library(psych)
```



```{r}
setwd("~/Desktop/PGP-BABI/Timeseries")
data = gas
str(data)
summary(data)
describe(data)
head(data)
tail(data)

#to check the NA values
plotNA.distribution(data)

#remove the NA values
data = tsclean(data,replace.missing = TRUE)

#To print the frequency of the series
frequency(data)

#To print the cycle across the series
cycle(data)

#To check the outliers
tsoutliers(data)

```

## Including Plots

You can also embed plots, for example:

```{r}
### Aggregation at a Quarter and Year Level

TSdata.qtr <- aggregate(data, nfrequency=4)
TSdata.yr <- aggregate(data, nfrequency=1)

### Plots

plot.ts(data, main = "Monthly Gas Production in Australia", xlab = "Time", ylab = "Gas Production")

plot.ts(TSdata.qtr, main = "Quarterly Gas Production in Australia", xlab = "Time", ylab = "Gas Production")

plot.ts(TSdata.yr, main = "Yearly Gas Production in Australia", xlab = "Time", ylab = "Gas Production")

### Seasonality Plot for further analysis

seasonplot(data, year.labels = TRUE, year.labels.left=TRUE, col=1:40, pch=19, main = "Monthly Gas Production in Australia - seasonplot", xlab = "Time", ylab = "Gas Production")

monthplot(data, main = "Monthly Gas Production in Australia - monthplot", xlab = "Time", ylab = "Gas Production")

boxplot(data ~ cycle(data), xlab = "Year", ylab = "Gas Production", main = "Australian monthly gas production from 1956 to 1995", col = "red")

#Moving average plots of the graph

plot(data, col="gray", main = "1 Year Moving Average Smoothing")+
lines(ma(data, order = 12), col = "red", lwd=3)
plot(data, col="gray", main = "3 Year Moving Average Smoothing")+
lines(ma(data, order = 36), col = "blue", lwd=3)
plot(data, col="gray", main = "5 Year Moving Average Smoothing")+
lines(ma(data, order = 60), col = "green", lwd=3)
plot(data, col="gray", main = "10 Year Moving Average Smoothing")+
lines(ma(data, order = 120), col = "yellow4", lwd=3)

plot.ts(log(data), main = "Log Transformated Australian Monthly gas production",
xlab = "Year", ylab = "ML")

tsdisplay(data)

ggAcf(data)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}


#Constant and non constant seasonality of the data
data.constant.seasonality = stl(data, s.window = "p")
plot(data.constant.seasonality , col = c("blue"))
print(data.constant.seasonality)

data.nonconstant.seasonality = stl(data , s.window = 7)
plot(data.nonconstant.seasonality, col = c("red"))
print(data.nonconstant.seasonality)


```

```{r}
plot(data)

#Augmented Dickey Fuller Test
adf.test(data)

#We find that the data is not stationary as the p value is not less than 0.05 which we had assumed for the null hypothesis.

## Our gas data is non-stationary; the average gas production changes through time.

diff_data_new <- diff(data) 
plot(diff_data_new)

adf.test(diff_data_new)
#from the initial test we conclude that p value is less than 0.05 so the data can be said to be stationary.
#We perform the PACF and ACF to test the further goodness of the data.
acf(diff_data_new)
pacf(diff_data_new)
```

```{r}
#Trying out smoothening model

## 1. SES

model_gas_ses <- HoltWinters(data,beta = FALSE, gamma = FALSE)
plot(model_gas_ses)
model_gas_ses #alpha = 0.99
SES_forecast <- forecast(model_gas_ses,12)
plot(SES_forecast)
#MAPE - 8.22


## 2. Holt Trend

model_gas_trend <- HoltWinters(data,gamma = FALSE)
plot(model_gas_trend)
Trend_forecast <- forecast(model_gas_trend,12)
plot(Trend_forecast)
#accuracy(Trend_forecast) # MAPE - 8.15


## 3. Holt Seasonal

model_gas_Seasonal <- HoltWinters(data)
plot(model_gas_Seasonal)
Seasonal_forecast <- forecast(model_gas_Seasonal,12)
plot(Seasonal_forecast)
#accuracy(Seasonal_forecast) #MAPE - 4.29


#Since the `alpha is 0.99` we are taking recent data for ARIMA model
#Choosing data from 1991 to 1995 


gas_recent <- ts(data[421:476],start = c(1991,1) , end = c(1995,8), frequency = 12)
plot(diff(log(gas_recent)))
kpss.test(diff(gas_recent))

pacf(diff(log(gas_recent))) #1
acf(diff(log(gas_recent))) #2
#  d = 1
```

```{r}
### Divide data into test and train 

DataATrain <- window(data, start=c(1970,1), end=c(1993,12), frequency=12) 
DataATest <- window(data, start=c(1994,1), frequency=12) 

#### ARIMA Model

TSdat.arima.fit.train <- auto.arima(DataATrain, seasonal=TRUE) 
TSdat.arima.fit.train

## estimated variance of the residual noise term, the log-likelihood 
## and various information criteria: the AIC, the small-sample corrected AICc and the BIC

fit <- Arima(DataATrain, c(1, 1, 1),seasonal = list(order = c(0, 1, 1), period = 12))

fit

plot(fit$x,col="blue", main="Production: Actual vs Forecast") +
lines(fit$fitted,col="red")

Box.test(fit$residuals, type = c("Ljung-Box"))

#### Conclusion: Do not reject H0: Residuals are independent

VecA1 <- cbind(fit$fitted,fit$x)

MAPEA_train <- mean(abs(VecA1[,1]-VecA1[,2])/VecA1[,1]) 
MAPEA_train

####Forecasting on hold dataset

Arimafcast <- forecast(fit, h=20)
VecA2 <- cbind(DataATest,Arimafcast)

MAPEA_holdout <- mean(abs(VecA2[,1]-VecA2[,2])/VecA2[,1]) 
MAPEA_holdout

ts.plot(VecA2[,1],VecA2[,2], col=c("blue","red"),xlab="year", ylab="production", main="Production: Actual vs Forecast")

### Forecasting using the entire data set


Final_model <- auto.arima(data, seasonal=TRUE)
Final_model 

Box.test(Final_model$residuals, type = c("Ljung-Box"))

Final_forecast <- forecast(Final_model, h=12) 
plot(Final_forecast)


```

